apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-education-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: online-education-app
  template:
    metadata:
      labels:
        app: online-education-app
    spec:
      containers:
      - name: online-education-app
        image: online-education-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: online-education-app-service
spec:
  type: NodePort
  selector:
    app: online-education-app
  ports:
    - port: 3000
      targetPort: 3000
